PRAGMA foreign_KEYs=ON;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS user;

CREATE TABLE user( 
    userid INTEGER PRIMARY KEY AUTOINCREMENT, 
    fname TEXT NOT NULL, 
    lname TEXT NOT NULL,
    username VARCHAR(25) NOT NULL, 
    passwrd VARCHAR(20) NOT NULL, 
    UNIQUE(username)
);

COMMIT;